(function(){'use strict';if(location.pathname!=='/admin.html')return;
let input,modal,video,controls=null,stream=null,scanning=false,busy=false;
const getInput=()=>document.getElementById('barcode');
const setMsg=t=>{const e=document.getElementById('adminScannerMsg');if(e)e.textContent=t};
function stop(){scanning=false;if(controls){try{controls.stop()}catch(e){}controls=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(video){video.pause();video.srcObject=null}if(modal)modal.style.display='none'}
function accept(code){code=String(code||'').trim();if(!code)return;input=getInput();if(!input)return;input.value=code;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));stop()}
function makeModal(){if(modal)return;modal=document.createElement('div');modal.id='adminScannerModal';modal.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.86);z-index:99999;display:none;align-items:center;justify-content:center;padding:14px;direction:rtl';modal.innerHTML='<div style="width:min(540px,100%);background:#fff;border-radius:20px;padding:15px"><div style="display:flex;justify-content:space-between;align-items:center"><strong>📷 سكان الباركود</strong><button id="closeAdminScanner" type="button">✕ إغلاق</button></div><div id="adminScannerMsg" style="margin:10px 0;color:#555">جاري التحضير...</div><div style="position:relative;background:#111;border-radius:14px;overflow:hidden"><video id="adminScannerVideo" playsinline autoplay muted style="display:block;width:100%;aspect-ratio:4/3;object-fit:cover"></video><div style="position:absolute;left:10%;right:10%;top:50%;height:2px;background:#d4af37;box-shadow:0 0 14px #d4af37"></div></div><button id="stopAdminScanner" type="button" style="margin-top:10px">⏹ إيقاف الكاميرا</button></div>';document.body.appendChild(modal);video=document.getElementById('adminScannerVideo');document.getElementById('closeAdminScanner').onclick=stop;document.getElementById('stopAdminScanner').onclick=stop}
function loadZXing(){return new Promise((resolve,reject)=>{if(window.ZXingBrowser)return resolve();const s=document.createElement('script');s.src='https://unpkg.com/@zxing/browser@0.1.5/umd/index.min.js';s.onload=()=>window.ZXingBrowser?resolve():reject(new Error('ZXing'));s.onerror=()=>reject(new Error('NETWORK'));document.head.appendChild(s)})}
function ensureButton(){input=getInput();if(!input)return false;makeModal();if(document.getElementById('adminScanBtn'))return true;const b=document.createElement('button');b.id='adminScanBtn';b.type='button';b.className='btn gold';b.textContent='📷 سكان الباركود';input.parentElement.appendChild(b);b.onclick=start;return true}
async function start(){if(busy)return;busy=true;input=getInput();makeModal();modal.style.display='flex';setMsg('جاري تشغيل الكاميرا...');try{if(!window.isSecureContext)throw new Error('HTTPS');if(!navigator.mediaDevices?.getUserMedia)throw new Error('CAMERA');await loadZXing();const reader=new ZXingBrowser.BrowserMultiFormatReader();const devices=await ZXingBrowser.BrowserCodeReader.listVideoInputDevices();if(!devices.length)throw new Error('NO_CAMERA');const cam=devices.find(d=>/back|rear|environment|arrière|trasera/i.test(d.label))||devices[devices.length-1];setMsg('الكاميرا تعمل… قرّب الباركود');controls=await reader.decodeFromVideoDevice(cam.deviceId,video,r=>{if(r&&scanning){scanning=false;accept(r.getText())}});scanning=true}catch(e){console.error(e);setMsg(e.message==='HTTPS'?'الكاميرا تحتاج HTTPS.':e.name==='NotAllowedError'?'تم رفض إذن الكاميرا. اسمح به من إعدادات المتصفح.':e.message==='NO_CAMERA'?'لم يتم العثور على كاميرا.':'تعذر تشغيل قارئ الباركود. تحقق من الاتصال والإذن.');stop()}finally{busy=false}}
function boot(){if(ensureButton())return;setTimeout(boot,250)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();new MutationObserver(()=>{if(!document.getElementById('adminScanBtn'))ensureButton()}).observe(document.documentElement,{childList:true,subtree:true});
})();