
-- MAISON AL TEEB product manager
-- Run this in Supabase SQL Editor.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  name_fr text,
  name_en text,
  category text not null,
  gender text default 'للجنسين',
  size text,
  price numeric(12,2) not null default 0,
  old_price numeric(12,2) not null default 0,
  discount integer not null default 0,
  image_url text,
  is_best_seller boolean not null default false,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Public can only read active products.
drop policy if exists "public read active products" on public.products;
create policy "public read active products"
on public.products for select
to anon, authenticated
using (active = true);

-- Admin writes: authenticated users.
-- For a single-owner store, create only your own Supabase Auth user.
drop policy if exists "authenticated insert products" on public.products;
create policy "authenticated insert products"
on public.products for insert
to authenticated
with check (true);

drop policy if exists "authenticated update products" on public.products;
create policy "authenticated update products"
on public.products for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated delete products" on public.products;
create policy "authenticated delete products"
on public.products for delete
to authenticated
using (true);

-- Storage bucket for product images.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public read product images" on storage.objects;
create policy "public read product images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'product-images');

drop policy if exists "authenticated upload product images" on storage.objects;
create policy "authenticated upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images');

drop policy if exists "authenticated update product images" on storage.objects;
create policy "authenticated update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'product-images')
with check (bucket_id = 'product-images');

drop policy if exists "authenticated delete product images" on storage.objects;
create policy "authenticated delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images');
