-- MAISON AL TEEB — Supabase schema / security baseline
-- Products are public-read when active. Product mutations require admin/manager roles.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  name_fr text,
  name_en text,
  category text not null,
  gender text default 'للجنسين',
  size text,
  price numeric(12,2) not null default 0,
  old_price numeric(12,2) not null default 0,
  discount integer not null default 0,
  image_url text,
  is_best_seller boolean not null default false,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'cashier' check (role in ('admin','manager','cashier')),
  created_at timestamptz not null default now()
);

create schema if not exists private;
create or replace function private.has_role(required_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = any(required_roles)
  );
$$;
revoke all on function private.has_role(text[]) from public, anon;
grant execute on function private.has_role(text[]) to authenticated;
drop function if exists public.has_role(text[]);
revoke all on function public.handle_new_user() from public, anon, authenticated;

alter table public.products enable row level security;

drop policy if exists "public read active products" on public.products;
drop policy if exists "Public can read active products" on public.products;
create policy "public read active products" on public.products for select to anon, authenticated using (active = true);

drop policy if exists "staff can read all products" on public.products;
create policy "staff can read all products" on public.products for select to authenticated using (private.has_role(array['admin','manager','cashier']::text[]));

drop policy if exists "authenticated insert products" on public.products;
drop policy if exists "managers can insert products" on public.products;
create policy "managers can insert products" on public.products for insert to authenticated with check (private.has_role(array['admin','manager']::text[]));

drop policy if exists "authenticated update products" on public.products;
drop policy if exists "managers can update products" on public.products;
create policy "managers can update products" on public.products for update to authenticated using (private.has_role(array['admin','manager']::text[])) with check (private.has_role(array['admin','manager']::text[]));

drop policy if exists "authenticated delete products" on public.products;
drop policy if exists "admins can delete products" on public.products;
create policy "admins can delete products" on public.products for delete to authenticated using (private.has_role(array['admin']::text[]));

insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true) on conflict (id) do update set public = true;

drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects for select to anon, authenticated using (bucket_id = 'product-images');

drop policy if exists "authenticated upload product images" on storage.objects;
drop policy if exists "managers upload product images" on storage.objects;
create policy "managers upload product images" on storage.objects for insert to authenticated with check (bucket_id='product-images' and private.has_role(array['admin','manager']::text[]));

drop policy if exists "authenticated update product images" on storage.objects;
drop policy if exists "managers update product images" on storage.objects;
create policy "managers update product images" on storage.objects for update to authenticated using (bucket_id='product-images' and private.has_role(array['admin','manager']::text[])) with check (bucket_id='product-images' and private.has_role(array['admin','manager']::text[]));

drop policy if exists "authenticated delete product images" on storage.objects;
drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects for delete to authenticated using (bucket_id='product-images' and private.has_role(array['admin']::text[]));

-- After creating the Supabase Auth user, assign the owner/admin role:
-- insert into public.profiles (id, role) values ('AUTH-USER-UUID', 'admin') on conflict (id) do update set role = 'admin';
